<?php

namespace Hsy\Shopy\Tests;

use Hsy\Shopy\Facades\Shopy;
use Hsy\Shopy\Models\Product;
use Illuminate\Foundation\Testing\RefreshDatabase;

class CartTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test  */
    public function add_to_cart()
    {
        $product = factory(Product::class)->create();
        Shopy::cart()->add($product, 100);
        $this->assertCount(1, Shopy::cart()->content());
    }

    /** @test  */
    public function add_to_cart_from_model()
    {
        $product = factory(Product::class)->create();
        $product->addToCart();
        $this->assertCount(1, Shopy::cart()->content());
    }

    /** @test  */
    public function price_total_amount()
    {
        $products = factory(Product::class, 20)->create();
        foreach ($products as $product) {
            Shopy::cart()->add($product, 10);
        }

        $this->assertEquals(
            $products->map(function ($item) {
                return $item->price * 10;
            })->sum(),
            Shopy::cart()->priceTotal()
        );
    }

    /** @test  */
    public function all_contents_count()
    {
        $products = factory(Product::class, 20)->create();
        foreach ($products as $product) {
            Shopy::cart()->add($product, 10);
        }

        $this->assertEquals(Shopy::cart()->count(), 200);
    }

    /** @test  */
    public function attach_products()
    {
        $product = factory(Product::class)->create();
        $product->addToCart();

        Shopy::cart()->attachProducts();

        $this->assertEquals(
            $product->id,
            Shopy::cart()->content()->first()->options->product->id
        );
    }
}
