<?php

namespace Hsy\Shopy\Tests;

use Hsy\Shopy\Facades\Shopy;
use Hsy\Shopy\Models\Order;
use Hsy\Shopy\Models\OrderItem;
use Hsy\Shopy\Models\Product;
use Illuminate\Foundation\Testing\RefreshDatabase;

class OrdersTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function cart_to_order()
    {
        $productsCount = 20;
        $products = factory(Product::class, $productsCount)->create();
        foreach ($products as $product) {
            Shopy::cart()->add($product, 10);
        }

        $invoiceFromCart = Shopy::cart()->toOrder();
        $order = Order::first();

        $this->assertEquals($order->attributes, $invoiceFromCart->attributes);
        $this->assertCount($productsCount, OrderItem::all());
    }

    /** @test */
    public function invoice_extra_data()
    {
        $faker = \Faker\Factory::create();
        $product = factory(Product::class)->create();
        $product->addToCart();

        $extraData = [
            'customer_name'    => $faker->name,
            'customer_email'   => $faker->email,
            'customer_address' => $faker->address,
        ];
        $invoiceFromCart = Shopy::cart()->toOrder($extraData);
        $this->assertEquals($extraData, Order::first()->extra_data);
    }
}
